import '../globals.css';
import { monaSans, ppSupplyMono } from '@/utils/fonts';
import { type Metadata } from 'next';
import { TRPCReactProvider } from '@/trpc/react';
import { Providers } from '@/utils/providers';

export const metadata: Metadata = {
  title: 'Attest UI',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${monaSans.variable} ${ppSupplyMono.variable}`}
      suppressHydrationWarning={true}
    >
      <body suppressHydrationWarning={true}>
        <TRPCReactProvider>
          <Providers>{children}</Providers>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
